### ISSUE TITLE
Transition modifier is removed

### ISSUE THREAD

**Issue by c0bra** [UnwrittenFun/prettier-plugin-svelte#34]
This is happening for me at the moment

`<div transition:fade|local>` -> `<div transition:fade>`

Not sure if it applies to all modifiers or just this one for transition.

**Comment by taylorzane** [comment]
#36 should resolve this problem for you.

**Comment by jSwtch** [comment]
This is still an issue.

<div transition:fade|local> -> <div transition:fade|local> OK

<div transition:fly|local> -> <div transition:fly>  not OK
<div transition:custom|local> -> <div transition:custom>  not OK

**Comment by lahickey** [comment]
Is there something I have to do to get this fix working with the VSCode-svelte plugin? This issue (https://github.com/UnwrittenFun/svelte-vscode/issues/51) is still happening.

**Comment by Koubi4cK** [comment]
Still having this issue with v3.0.0
